-- (frFR) localization stub.

local L = LibStub("AceLocale-3.0"):NewLocale("CritMatic", "frFR")
if not L then return end

--CritMatic.lua
L["action_bar_crit"] = "Crit"
L["action_bar_hit"] = "Coup"
L["action_bar_dps"] = " DPS"
L["action_bar_crit_heal"] = "Soin Critique"
L["action_bar_heal"] = "Soin"
L["action_bar_hps"] = " SPS"
L["new_version_notification"] = "Une version mise à jour de CritMatic a été publiée. Nous vous recommandons fortement de passer à la dernière version pour bénéficier de ses fonctionnalités améliorées et de sa stabilité."
L["new_version_notification_part"] = "La mise à jour est disponible sur CurseForge, Wago.io"
L["slash_cmlog"] = "cmlog"
L["slash_cmcritlog"] = "cmcritlog"
L["slash_cmignore"] = "cmignore"
L["slash_cmignoretarget"] = "cmignoretarget"
L["slash_cmreset"] = "cmreset"
L["version_string"] = "v"
L["critmatic_loaded"] = "Chargé ! - Utilisez"
L["critmatic_loaded_for_options"] = "pour les options -"
L["critmatic_loaded_cmhelp"] = " /cmhelp"
L["critmatic_loaded_for_all_slash_commands"] = "pour toute commande slash"
L["critmatic_reset"] = "Données réinitialisées !"
L["chat_crit"] = "Nouveau record de crit pour "
L["chat_hit"] = "Nouveau record de coup pour "
L["chat_crit_heal"] = "Nouveau record de soin critique pour "
L["chat_heal"] = "Nouveau record de soin pour "
L["social_crit"] = "Nouveau record de crit pour "
L["social_crit_heal"] = "Nouveau record de soin critique pour "
-- CritLog.lua
L["crit_log_crit"] = "Crit"
L["crit_log_hit"] = "Coup"
L["crit_log_heal"] = "Soin"
L["crit_log_new"] = "Nouveau"
L["crit_log_old"] = "Ancien"


-- CritMaticOptions.lua
-- General
L["options_general"] = "Général"
L["options_show_chat_notifications"] = "Afficher les notifications dans le chat"
L["options_show_chat_notifications_desc"] = "Voulez-vous afficher des messages pour les nouveaux records de crit/coup/soin dans votre fenêtre de chat?"
L["options_show_alert_notifications"] = "Afficher les alertes"
L["options_show_alert_notifications_desc"] = "Voulez-vous afficher des alertes pour les nouveaux records de crit/coup/soin?"
L["options_show_crit_log"] = "Afficher l'historique de crit"
L["options_show_crit_log_desc"] = "Affiche ou masque l'historique des crits récents."
L["options_show_change_log"] = "Afficher les notes de MàJ"
L["options_show_change_log_desc"] = "Voulez-vous voir les notes de mise à jour de CritMatic automatiquement?"
L["options_discord_link"] = "Aide/Suggestions: Copiez le lien du Discord de CritMatic"
L["options_discord_link_desc"] = "Demandez de l'aide ou faites une suggestion sur le Discord de CritMatic."
L["options_discord_link_copy"] = "Copier le lien du Discord"
-- Chat and Alert Notification Settings
L["options_alert_chat_notification_format_upper"] = "Majuscules"
L["options_alert_chat_notification_format_crit"] = "Crit"
L["options_alert_chat_notification_format_crit_desc"] = "Entrez votre propre format de notification pour les crits. Utilisez %s pour le nom du sort et %d pour le montant."
L["options_alert_chat_notification_format_hit"] = "Coup"
L["options_alert_chat_notification_format_hit_desc"] = "Entrez votre propre format de notification pour les coups. Utilisez %s pour le nom du sort et %d pour le montant."
L["options_alert_chat_notification_format_crit_heal"] = "Soin Critique"
L["options_alert_chat_notification_format_crit_heal_desc"] = "Entrez votre propre format de notification pour les soins critiques. Utilisez %s pour le nom du sort et %d pour le montant."
L["options_alert_chat_notification_format_heal"] = "Soin"
L["options_alert_chat_notification_format_heal_desc"] = "Entrez votre propre format de notification pour les soins. Utilisez %s pour le nom du sort et %d pour le montant."

-- Alert Notification Format Settings
L["options_alert_notification_format"] = "Alertes"
L["options_alert_notification_format_upper_desc"] = "Cochez pour utiliser uniquement des majuscules.  défaut: coché"
L["options_alert_notification_format_desc"] = "Choisissez le format pour vos alertes."
L["options_alert_notification_format_reset"] = "Réinitialiser les alertes"
L["options_alert_notification_format_reset_desc"] = "Réinitialiser tous les paramètres de format d'alerte à leurs valeurs par défaut?"
L["options_alert_notification_format_reset_confirm"] = "Êtes-vous sûr de vouloir réinitialiser les paramètres de format d'alerte à leurs valeurs par défaut?"

-- Chat Notification Format Settings
L["options_chat_notification_format"] = "Notifications du chat"
L["options_chat_notification_format_upper_desc"] = "Cochez pour utiliser uniquement des majuscules.  défaut: coché"
L["options_chat_notification_format_desc"] = "Choisissez le format pour vos notifications de chat."
L["options_chat_notification_format_reset"] = "Réinitialiser les notifications de chat"
L["options_chat_notification_format_reset_desc"] = "Réinitialiser tous les paramètres de format de notification de chat à leurs valeurs par défaut?"
L["options_chat_notification_format_reset_confirm"] = "Êtes-vous sûr de vouloir réinitialiser les paramètres de format de notification de chat à leurs valeurs par défaut?"

-- Font Settings uses the same font settings as the alert notification format
L["options_alert_font_settings"] = "Alerte"
L["options_alert_font"] = "Police (Vous devrez peut-être choisir une police deux fois pour voir toutes les polices.)"
L["options_alert_font_desc"] = "Vous devrez peut-être choisir une police deux fois pour voir toutes les polices."
L["options_alert_font_size"] = "Taille de la police"
L["options_alert_font_color_crit"] = "Couleur des critiques"
L["options_alert_font_color_crit_desc"] = "Choisissez une couleur pour les critiques."
L["options_alert_font_c_non_crit"] = "Couleur des non-critiques"
L["options_alert_font_c_non_crit_desc"] = "Choisissez une couleur pour les non-critiques."
L["options_alert_font_outline"] = "Contour"
L["options_alert_font_none"] = "Aucun"
L["options_alert_font_outline_mono"] = "Contour Monochrome"
L["options_alert_font_outline_thick"] = "Contour Épais"
L["options_alert_font_outline_thick_mono"] = "Contour Épais Monochrome"
L["options_alert_font_shadow_x"] = "Taille de l'Ombre X"
L["options_alert_font_shadow_x_desc"] = "Définissez la taille de l'ombre pour la police dans la direction horizontale."
L["options_alert_font_shadow_y"] = "Taille de l'Ombre Y"
L["options_alert_font_shadow_y_desc"] = "Définissez la taille de l'ombre pour la police dans la direction verticale."
L["options_alert_font_shadow_color"] = "Couleur de l'Ombre"
L["options_alert_font_shadow_color_desc"] = "Choisissez une couleur pour l'ombre de votre police."
L["options_alert_font_reset"] = "Réinitialiser les options de police"
L["options_alert_font_reset_desc"] = "Réinitialiser toutes les options de police à leurs valeurs par défaut"
L["options_alert_font_reset_confirm"] = "Êtes-vous sûr de vouloir réinitialiser les options de police à leurs valeurs par défaut?"

-- Sound Settings
L["options_sound_settings"] = "Sons"
L["options_sound_crit"] = "Son des crits"
L["options_sound_hit"] = "Son des coups"
L["options_sound_crit_heal"] = "Son des soins critiques"
L["options_sound_heal"] = "Son des soins"
L["options_sound_mute_all"] = "Couper tous les sons"
L["options_sound_mute_all_desc"] = "Voulez-vous rendre tous les sons muets indépendamment des paramètres?"
L["options_sound_reset"] = "Réinitialiser les Sons"
L["options_sound_reset_desc"] = "Réinitialiser tous les sons à leur configuration par défaut"
L["options_sound_reset_confirm"] = "Êtes-vous sûr de vouloir réinitialiser les paramètres sonores à leurs valeurs par défaut?"

-- Social Settings
L["options_social"] = "Social"
L["options_social_send_crits_toParty"] = "Envoyer les crits au groupe"
L["options_social_send_crits_toParty_desc"] = "Voulez-vous envoyer des messages en chat de groupe lorsque vous obtenez un coup critique? Par défaut: Coché"
L["options_social_send_crits_toRaid"] = "Envoyer les crits au raid"
L["options_social_send_crits_toRaid_desc"] = "Voulez-vous envoyer des messages en chat de raid lorsque vous obtenez un coup critique? Par défaut: Coché"
L["options_social_send_crits_toGuild"] = "Envoyer les crits à la guilde"
L["options_social_send_crits_toGuild_desc"] = "Voulez-vous envoyer des messages en chat de guilde lorsque vous obtenez un coup critique? Par défaut: Non-Coché"
L["options_social_send_crits_toBattleGrounds"] = "Envoyer les crits aux champs de bataille"
L["options_social_send_crits_toBattleGrounds_desc"] = "Voulez-vous envoyer des messages en chat de champ de bataille lorsque vous obtenez un coup critique? Par défaut: Coché"

-- Change Log Settings
L["options_change_log"] = "Notes de MàJ"
L["options_change_log_font"] = "Police"
L["options_change_log_font_desc"] = "Vous devrez peut-être choisir une police deux fois pour voir toutes les polices."
L["options_change_log_font_size"] = "Taille de la police"
L["options_change_log_font_color"] = "Couleur de la police"
L["options_change_log_font_color_desc"] = "Choisissez une couleur de police."
L["options_change_log_font_outline"] = "Contour"
L["options_change_log_font_none"] = "Aucun"
L["options_change_log_font_outline_mono"] = "Contour Monochrome"
L["options_change_log_font_outline_thick"] = "Contour Épais"
L["options_change_log_font_outline_thick_mono"] = "Contour Épais Monochrome"
L["options_change_log_reset"] = "Réinitialiser les Paramètres de Police des notes de MàJ"
L["options_change_log_reset_desc"] = "Réinitialiser les Paramètres de Police des notes de MàJ à leurs valeurs par défaut?"
L["options_change_log_reset_confirm"] = "Êtes-vous sûr de vouloir réinitialiser les paramètres de police des notes de MàJ à leurs valeurs par défaut?"

L["options_change_log_border_and_background"] = "Bordure et Fond"
L["options_change_log_border_and_background_border"] = "Texture de la Bordure"
L["options_change_log_border_and_background_border_desc"] = "Choisissez une texture de bordure dans la liste. Nécessite un rechargement"
L["options_change_log_border_and_background_border_size"] = "Taille de la Bordure"
L["options_change_log_border_and_background_border_size_desc"] = "Définissez la taille de la bordure pour le cadre de bordure. Nécessite un rechargement"
L["options_change_log_border_and_background_texture"] = "Texture du Fond"
L["options_change_log_border_and_background_texture_desc"] = "Choisissez une texture de fond dans la liste. Nécessite un rechargement"
L["options_change_log_border_and_background_reset"] = "Réinitialiser les Paramètres de Bordure et de Fond des notes de MàJ"
L["options_change_log_border_and_background_reset_desc"] = "Réinitialiser tous les paramètres de bordure et de fond des notes de MàJ à leurs valeurs par défaut?"
L["options_change_log_border_and_background_reset_confirm"] = "Êtes-vous sûr de vouloir réinitialiser les paramètres de bordure et de fond des notes de MàJ à leurs valeurs par défaut?"

-- Ignored Spells Settings
L["options_ignored_spells"] = "Sorts Ignorés"
L["options_ignored_spells_desc"] = "Gérez les sorts que CritMatic ignore. Vous pouvez également ignorer les sorts en faisant un clic droit dessus dans le journal des critiques ou en utilisant /cmignore nom-du-sort."
L["options_ignored_spells_select"] = "Sélectionner un Sort"
L["options_ignored_spells_remove"] = "Supprimer la Sélection"
L["options_ignored_spells_clear_all"] = "Effacer tous les Sorts Ignorés"
L["options_ignored_spells_clear_all_confirm"] = "Êtes-vous sûr de vouloir supprimer tous les sorts ignorés?"
